### ISSUE TITLE
Add missing navbar code

### ISSUE THREAD

**Issue by ghermans** [idevelopment/officeportal#38]
```css
.navbar-default .navbar-nav > li > a:hover, .navbar-default .navbar-nav > li > a:focus {
    background-color: #016B8F;
    color: #fff;
}

.navbar-default .navbar-nav > .open{
   color: #fff;
  background: #016B8F;
}
.navbar-default .navbar-nav > .open > a,
.navbar-default .navbar-nav > .open > a:hover,
.navbar-default .navbar-nav > .open > a:focus {
     color: #fff;
     background: #016B8F;
}
```
